name: KPI LINE Alert

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer axios

      - name: Run KPI Alert Script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
        run: node main.js
